# K-MEANS CLUSTERING


In [1]:
import cv2
import numpy as np

In [2]:
im1=cv2.imread("tvs2.jpg")


In [3]:
im1


array([[[255, 253, 252],
        [254, 250, 249],
        [255, 255, 251],
        ...,
        [ 50, 103, 113],
        [ 45,  85,  97],
        [ 13,  47,  60]],

       [[251, 247, 246],
        [255, 255, 254],
        [248, 245, 241],
        ...,
        [ 32,  87,  94],
        [ 25,  67,  79],
        [ 26,  65,  74]],

       [[255, 253, 252],
        [252, 250, 249],
        [255, 254, 253],
        ...,
        [ 41,  99, 104],
        [ 20,  69,  77],
        [ 39,  87,  93]],

       ...,

       [[157, 166, 176],
        [166, 175, 185],
        [171, 180, 190],
        ...,
        [110, 114, 125],
        [107, 111, 122],
        [103, 107, 118]],

       [[160, 170, 180],
        [168, 178, 188],
        [162, 172, 182],
        ...,
        [104, 109, 118],
        [104, 109, 118],
        [100, 105, 114]],

       [[161, 171, 181],
        [167, 177, 187],
        [150, 160, 170],
        ...,
        [ 98, 103, 112],
        [ 97, 102, 111],
        [ 90,  95, 104]]

In [4]:
imgrgb= cv2.cvtColor(im1,cv2.COLOR_BGR2RGB) #color conversion

In [5]:
vec=imgrgb.reshape((-1,3)) #image reshaping

In [6]:
vec

array([[252, 253, 255],
       [249, 250, 254],
       [251, 255, 255],
       ...,
       [112, 103,  98],
       [111, 102,  97],
       [104,  95,  90]], dtype=uint8)

In [7]:
vec=np.float32(vec) #float conversion
vec

array([[252., 253., 255.],
       [249., 250., 254.],
       [251., 255., 255.],
       ...,
       [112., 103.,  98.],
       [111., 102.,  97.],
       [104.,  95.,  90.]], dtype=float32)

## iteration termination criteria 

In [8]:
criteria= (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,100,1)

## cluster conditions 

In [9]:
k=10
attempts=100

## k-means clustering

In [10]:
compactness,label,center =cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)

In [11]:
compactness,label,center

(25930767.4547759,
 array([[5],
        [5],
        [5],
        ...,
        [0],
        [0],
        [0]], dtype=int32),
 array([[115.90675 , 108.36325 ,  90.91807 ],
        [ 13.38734 ,  11.365871,   8.739358],
        [178.12659 , 167.47238 , 158.20357 ],
        [ 44.73143 ,  42.095974,  21.004204],
        [149.47752 , 138.32704 , 125.6122  ],
        [225.73608 , 224.71785 , 222.43666 ],
        [108.42637 , 103.2928  ,  43.404934],
        [205.36702 , 151.27629 ,  42.63505 ],
        [ 77.42585 ,  72.65263 ,  61.605247],
        [ 75.67924 ,  72.75593 ,  23.260874]], dtype=float32))

In [12]:
center =np.uint8(center)
center

array([[115, 108,  90],
       [ 13,  11,   8],
       [178, 167, 158],
       [ 44,  42,  21],
       [149, 138, 125],
       [225, 224, 222],
       [108, 103,  43],
       [205, 151,  42],
       [ 77,  72,  61],
       [ 75,  72,  23]], dtype=uint8)

# flattening and reshaping

In [13]:
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[225, 224, 222],
        [225, 224, 222],
        [225, 224, 222],
        ...,
        [108, 103,  43],
        [108, 103,  43],
        [ 44,  42,  21]],

       [[225, 224, 222],
        [225, 224, 222],
        [225, 224, 222],
        ...,
        [108, 103,  43],
        [ 75,  72,  23],
        [ 75,  72,  23]],

       [[225, 224, 222],
        [225, 224, 222],
        [225, 224, 222],
        ...,
        [108, 103,  43],
        [ 75,  72,  23],
        [108, 103,  43]],

       ...,

       [[178, 167, 158],
        [178, 167, 158],
        [178, 167, 158],
        ...,
        [115, 108,  90],
        [115, 108,  90],
        [115, 108,  90]],

       [[178, 167, 158],
        [178, 167, 158],
        [178, 167, 158],
        ...,
        [115, 108,  90],
        [115, 108,  90],
        [115, 108,  90]],

       [[178, 167, 158],
        [178, 167, 158],
        [178, 167, 158],
        ...,
        [115, 108,  90],
        [115, 108,  90],
        [115, 108,  90]]

In [14]:
cv2.imshow('image',im1)
cv2.imshow('segmented',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [15]:
cv2.imwrite('segmented.jpg',res_img)

True